### PR TITLE
RTL support

### PR DESCRIPTION
**Pull request by jjeem**
### Add RTL support for components:

- Breadcrumb
- Input OTP
- Calendar

### CODE REVIEW

**Comment by jjeem** [comment]
I had a look today at the chart component and looks like it doesn't require any changes (RTL support should be done through Recharts lib rather than shadcn). And the Sidebar component is missing since this repo is behind in commits. Can you please sync the repo if you have some time so that I can continue?

And this PR should be ready now for review.

**Comment by jjeem** [comment]
@nahasco

**Comment by nahasco** [comment]
Thanks for the great work. I never got notified about this pull request so thanks for the mention.

**Comment by nahasco** [comment]
I just synced the fork. @jjeem

**Comment by jjeem** [comment]
Thank you. I'll try to finish it as soon as I can

**Pull request merged**
