### PR TITLE
Sidebar RTL support

### PR DESCRIPTION
**Pull request by jjeem**
- Adds RTL support for Sidebar
- Lists `@radix-ui/react-direction` as a dependency for the Sidebar component

### CODE REVIEW

**Comment by jjeem** [comment]
@nahasco this is ready

**Comment by nahasco** [comment]
Thanks for your contribution. I will test and get back to you.

**Comment by jjeem** [comment]
Take your time and thanks for the opportunity 👍

**Comment by nahasco** [comment]
The sidebar components themselves now support RTL, but the blocks don't. I think the sidebar blocks are essential to the sidebar component. If you have the time you may also work on that. Thanks!

**Comment by jjeem** [comment]
Yeah this makes sense. Unfortunately I don't think I can do it in the meantime.

**Pull request merged**
